// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzGaSMQ5aYEiAEuLNFwtRveHoQIex2bU',
    appId: '1:1009391916977:web:7a9677b28a0a9556830f90',
    messagingSenderId: '1009391916977',
    projectId: 'gateapp-239bc',
    authDomain: 'gateapp-239bc.firebaseapp.com',
    storageBucket: 'gateapp-239bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlrMc1koEYQhlJL4hxln2ccryNnMVGLU',
    appId: '1:1009391916977:android:57b52658cfed3b45830f90',
    messagingSenderId: '1009391916977',
    projectId: 'gateapp-239bc',
    storageBucket: 'gateapp-239bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJeRDc9wIC52wsl4ym2Ja0ggO-de5paDQ',
    appId: '1:1009391916977:ios:c109c05b5744a067830f90',
    messagingSenderId: '1009391916977',
    projectId: 'gateapp-239bc',
    storageBucket: 'gateapp-239bc.appspot.com',
    iosBundleId: 'com.example.gated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJeRDc9wIC52wsl4ym2Ja0ggO-de5paDQ',
    appId: '1:1009391916977:ios:719812db4af3c410830f90',
    messagingSenderId: '1009391916977',
    projectId: 'gateapp-239bc',
    storageBucket: 'gateapp-239bc.appspot.com',
    iosBundleId: 'com.example.gated.RunnerTests',
  );
}
